#!/usr/bin/make

CC = gcc
TARGET = ctpl # rename to mustpl
#LDFLAGS = -Wall
LDFLAGS = -static -s -Wall
CFLAGS = -c -fPIC -Wall -Wextra -g -std=gnu99 -Os
APP_VERSION ?= 0.0.0-undefined

.PHONY: all src/version.h $(TARGET) clean
all: $(TARGET)

$(TARGET): obj/cjson.o obj/mustach-cjson.o obj/mustach.o obj/mustach-wrap.o obj/utils.o obj/cli.o obj/main.o
	$(CC) $(LDFLAGS) -o $(TARGET) $(wildcard obj/*.o)
	@file $(TARGET)
	#upx -2 $(TARGET)

src/version.h:
	@printf '// Code generated by `make version.h`; DO NOT EDIT.\n\n#define APP_VERSION "%s"\n' "$(APP_VERSION)" > $@

obj/utils.o: src/utils.c
	$(CC) $(CFLAGS) -o $@ $<

obj/cli.o: src/cli.c src/version.h
	$(CC) $(CFLAGS) -o $@ $<

obj/main.o: src/main.c
	$(CC) $(CFLAGS) -o $@ $<

obj/cjson.o: src/cjson/cJSON.c
	$(CC) $(CFLAGS) -o $@ $<

obj/mustach.o: src/mustach/mustach.c
	$(CC) $(CFLAGS) -o $@ $<

obj/mustach-wrap.o: src/mustach/mustach-wrap.c
	$(CC) $(CFLAGS) -o $@ $<

obj/mustach-cjson.o: src/mustach/mustach-cjson.c
	$(CC) $(CFLAGS) -o $@ $<

test: $(TARGET) ## Run tests
	@set -e; for n in $(wildcard tests/*); do \
		$(MAKE) -C $$n test clean; \
	done

clean: ## Cleaning
	-rm $(TARGET) src/version.h obj/*.o
